# This file is auto-generated. Do not modify manually.
plugin_registry = {
    "linear_general": "jax2onnx.converter.plugins.flax.nnx.linear_general",
    "add": "jax2onnx.converter.plugins.jax.lax.add",
    "and": "jax2onnx.converter.plugins.jax.lax.and_",
    "argmax": "jax2onnx.converter.plugins.jax.lax.argmax",
    "argmin": "jax2onnx.converter.plugins.jax.lax.argmin",
    "div": "jax2onnx.converter.plugins.jax.lax.div",
    "dot_general": "jax2onnx.converter.plugins.jax.lax.dot_general",
    "eq": "jax2onnx.converter.plugins.jax.lax.eq",
    "exp": "jax2onnx.converter.plugins.jax.lax.exp",
    "gather": "jax2onnx.converter.plugins.jax.lax.gather",
    "gt": "jax2onnx.converter.plugins.jax.lax.gt",
    "integer_pow": "jax2onnx.converter.plugins.jax.lax.integer_pow",
    "iota": "jax2onnx.converter.plugins.jax.lax.iota",
    "log": "jax2onnx.converter.plugins.jax.lax.log",
    "lt": "jax2onnx.converter.plugins.jax.lax.lt",
    "max": "jax2onnx.converter.plugins.jax.lax.max",
    "min": "jax2onnx.converter.plugins.jax.lax.min",
    "mul": "jax2onnx.converter.plugins.jax.lax.mul",
    "ne": "jax2onnx.converter.plugins.jax.lax.ne",
    "not": "jax2onnx.converter.plugins.jax.lax.not_",
    "or": "jax2onnx.converter.plugins.jax.lax.or_",
    "reduce_max": "jax2onnx.converter.plugins.jax.lax.reduce_max",
    "reduce_min": "jax2onnx.converter.plugins.jax.lax.reduce_min",
    "reduce_sum": "jax2onnx.converter.plugins.jax.lax.reduce_sum",
    "scatter-add": "jax2onnx.converter.plugins.jax.lax.scatter_add",
    "select_n": "jax2onnx.converter.plugins.jax.lax.select_n",
    "sqrt": "jax2onnx.converter.plugins.jax.lax.sqrt",
    "square": "jax2onnx.converter.plugins.jax.lax.square",
    "sub": "jax2onnx.converter.plugins.jax.lax.sub",
    "tanh": "jax2onnx.converter.plugins.jax.lax.tanh",
    "xor": "jax2onnx.converter.plugins.jax.lax.xor",
}
