# tests/extra_tests/framework/test_coverage_docs.py

"""Guard generated component coverage docs against internal drift."""

from __future__ import annotations

from collections import Counter
from pathlib import Path
import re
from typing import Final

REPO_ROOT = Path(__file__).resolve().parents[3]

SNAPSHOT_RE: Final = re.compile(r"^- (?P<label>.+?): `(?P<count>\d+)`$")
ROW_RE: Final = re.compile(
    r"^\| \[(?P<check>[ x])\] \| `(?P<name>[^`]+)` \| "
    r"`(?P<status>[^`]+)` \| `(?P<modules>[^`]*)` \| (?P<note>.*) \|$"
)
ONNX_MAIN_ROW_RE: Final = re.compile(
    r"^\| \[(?P<op>[A-Za-z0-9_]+)\]"
    r"\(https://onnx\.ai/onnx/operators/onnx__[A-Za-z0-9_]+\.html\) \| "
    r"(?P<in_plugins>[^|]+) \| (?P<metadata>[^|]+) \| "
    r"(?P<lowering>[^|]+) \| (?P<modules>[^|]+) \| "
    r"(?P<candidates>[^|]+) \| (?P<next_action>[^|]+) \|$"
)
ONNX_EXTRA_ROW_RE: Final = re.compile(
    r"^\| `(?P<name>[^`]+)` \| (?P<metadata>[^|]+) \| "
    r"(?P<lowering>[^|]+) \| (?P<modules>[^|]+) \| "
    r"(?P<candidates>[^|]+) \| (?P<next_action>[^|]+) \|$"
)
ONNX_ACTION_BUCKET_RE: Final = re.compile(r"^  - (?P<label>[^:]+): `(?P<count>\d+)`$")
ONNX_CHECK: Final = "\u2705"
ONNX_EMPTY: Final = "\u2796"
COMPONENT_COVERAGE_MISSING_STATUSES: Final = {
    "docs/user_guide/jax_lax_coverage.md": {"missing", "missing_linalg"},
    "docs/user_guide/jax_numpy_coverage.md": {"missing"},
    "docs/user_guide/flax_api_coverage.md": {"missing"},
    "docs/user_guide/equinox_nn_coverage.md": {"missing"},
}


def _read_doc(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def _snapshot_counts(text: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for line in text.splitlines():
        match = SNAPSHOT_RE.match(line)
        if match is not None:
            counts[match.group("label")] = int(match.group("count"))
    return counts


def _table_rows(text: str) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for line in text.splitlines():
        match = ROW_RE.match(line)
        if match is not None:
            rows.append(
                (
                    match.group("check"),
                    match.group("name"),
                    match.group("status"),
                )
            )
    return rows


def _onnx_main_rows(text: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for line in text.splitlines():
        match = ONNX_MAIN_ROW_RE.match(line)
        if match is not None:
            rows.append(
                {key: value.strip() for key, value in match.groupdict().items()}
            )
    return rows


def _onnx_extra_rows(text: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    in_extra_section = False
    for line in text.splitlines():
        if line == "<!-- AUTOGENERATED ONNX OPERATOR EXTRA START -->":
            in_extra_section = True
            continue
        if line == "<!-- AUTOGENERATED ONNX OPERATOR EXTRA END -->":
            break
        if not in_extra_section:
            continue
        match = ONNX_EXTRA_ROW_RE.match(line)
        if match is not None:
            rows.append(
                {key: value.strip() for key, value in match.groupdict().items()}
            )
    return rows


def _onnx_action_buckets(text: str) -> dict[str, int]:
    buckets: dict[str, int] = {}
    for line in text.splitlines():
        match = ONNX_ACTION_BUCKET_RE.match(line)
        if match is not None:
            buckets[match.group("label")] = int(match.group("count"))
    return buckets


def _assert_doc_counts(
    *,
    relative_path: str,
    status_labels: dict[str, str],
    checked_statuses: set[str],
    unchecked_statuses: set[str],
    total_label: str,
    derived_counts: dict[str, int] | None = None,
) -> None:
    text = _read_doc(relative_path)
    assert "## Snapshot" in text
    assert "## Full Checklist" in text

    snapshot = _snapshot_counts(text)
    rows = _table_rows(text)
    assert rows, f"{relative_path} has no coverage table rows"

    statuses = Counter(status for _, _, status in rows)
    expected_statuses = (
        set(status_labels.values()) | checked_statuses | unchecked_statuses
    )
    assert set(statuses) <= expected_statuses
    assert snapshot[total_label] == len(rows)

    for label, status in status_labels.items():
        assert snapshot[label] == statuses[status]

    for label, expected in (derived_counts or {}).items():
        assert snapshot[label] == expected

    for checkbox, name, status in rows:
        if status in checked_statuses:
            assert checkbox == "x", f"{relative_path}: {name} should be checked"
        elif status in unchecked_statuses:
            assert checkbox == " ", f"{relative_path}: {name} should be unchecked"
        else:
            raise AssertionError(
                f"{relative_path}: unknown status {status!r} for {name}"
            )


def test_jax_lax_coverage_doc_snapshot_matches_table() -> None:
    _assert_doc_counts(
        relative_path="docs/user_guide/jax_lax_coverage.md",
        total_label="Total docs operators",
        status_labels={
            "Covered (direct plugin)": "covered",
            "Covered (via alias primitive)": "covered_indirect",
            "Composite/helper (no standalone plugin expected)": "composite",
            "Out of scope (distributed/token/host)": "out_of_scope",
            "Missing primitive plugins": "missing",
            "Missing `lax.linalg` plugins": "missing_linalg",
        },
        checked_statuses={
            "covered",
            "covered_indirect",
            "composite",
            "out_of_scope",
        },
        unchecked_statuses={"missing", "missing_linalg"},
    )


def test_jax_numpy_coverage_doc_snapshot_matches_table() -> None:
    _assert_doc_counts(
        relative_path="docs/user_guide/jax_numpy_coverage.md",
        total_label="Total docs entries",
        status_labels={
            "Covered (direct plugin)": "covered",
            "Covered (via alias/indirect signal)": "covered_indirect",
            "Composite/helper entries": "composite",
            "Non-functional entries (dtype/type/constants)": "non_functional",
            "Missing dedicated plugin coverage": "missing",
        },
        checked_statuses={
            "covered",
            "covered_indirect",
            "composite",
            "non_functional",
        },
        unchecked_statuses={"missing"},
    )


def test_flax_api_coverage_doc_snapshot_matches_table() -> None:
    text = _read_doc("docs/user_guide/flax_api_coverage.md")
    statuses = Counter(status for _, _, status in _table_rows(text))
    in_scope_count = (
        statuses["covered"]
        + statuses["covered_indirect"]
        + statuses["composite"]
        + statuses["missing"]
    )

    _assert_doc_counts(
        relative_path="docs/user_guide/flax_api_coverage.md",
        total_label="Total API entries discovered",
        status_labels={
            "Covered (direct Flax plugin)": "covered",
            "Covered (indirect via lower-level plugins)": "covered_indirect",
            "Composite/helper entries": "composite",
            "Out-of-scope entries": "out_of_scope",
            "Missing dedicated Flax coverage": "missing",
        },
        derived_counts={
            "In-scope neural entries (`flax.linen/*`, `flax.nnx/nn/*`)": in_scope_count,
        },
        checked_statuses={
            "covered",
            "covered_indirect",
            "composite",
            "out_of_scope",
        },
        unchecked_statuses={"missing"},
    )


def test_equinox_nn_coverage_doc_snapshot_matches_table() -> None:
    _assert_doc_counts(
        relative_path="docs/user_guide/equinox_nn_coverage.md",
        total_label="Total Equinox nn API entries",
        status_labels={
            "Covered (direct Equinox plugin)": "covered",
            "Covered (indirect signal)": "covered_indirect",
            "Composite/helper entries": "composite",
            "Out-of-scope state/inference entries": "out_of_scope",
            "Missing dedicated Equinox coverage": "missing",
        },
        checked_statuses={
            "covered",
            "covered_indirect",
            "composite",
            "out_of_scope",
        },
        unchecked_statuses={"missing"},
    )


def test_component_coverage_docs_have_no_open_missing_entries() -> None:
    failures: list[str] = []
    for relative_path, missing_statuses in COMPONENT_COVERAGE_MISSING_STATUSES.items():
        rows = _table_rows(_read_doc(relative_path))
        missing_rows = [
            f"{name} ({status})"
            for _, name, status in rows
            if status in missing_statuses
        ]
        if missing_rows:
            failures.append(f"{relative_path}: {', '.join(missing_rows)}")

    assert not failures, "Component coverage docs should stay complete:\n" + "\n".join(
        failures
    )


def test_onnx_operator_coverage_doc_summary_matches_tables() -> None:
    text = _read_doc("docs/user_guide/onnx_operator_coverage.md")
    assert "<!-- AUTOGENERATED ONNX OPERATOR TABLE START -->" in text
    assert "<!-- AUTOGENERATED ONNX OPERATOR TABLE END -->" in text
    assert "<!-- AUTOGENERATED ONNX OPERATOR EXTRA START -->" in text
    assert "<!-- AUTOGENERATED ONNX OPERATOR EXTRA END -->" in text

    summary = _snapshot_counts(text)
    main_rows = _onnx_main_rows(text)
    extra_rows = _onnx_extra_rows(text)
    referenced_rows = [row for row in main_rows if row["in_plugins"] == ONNX_CHECK]
    action_buckets = _onnx_action_buckets(text)

    assert main_rows, "ONNX operator coverage has no main table rows"
    assert summary["Operators in index"] == len(main_rows)
    assert summary["Operators referenced in plugins"] == len(referenced_rows)
    assert summary["Extra plugin names not present in index"] == len(extra_rows)
    assert action_buckets, "ONNX operator coverage has no action buckets"
    assert sum(action_buckets.values()) == len(main_rows) - len(referenced_rows)

    expected_coverage = f"{len(referenced_rows) / len(main_rows):.1%}"
    assert f"- Coverage: `{expected_coverage}`" in text

    for row in main_rows:
        has_metadata = row["metadata"] == ONNX_CHECK
        has_lowering = row["lowering"] == ONNX_CHECK
        has_plugins = row["in_plugins"] == ONNX_CHECK
        assert has_plugins == (has_metadata or has_lowering), row["op"]
        assert (row["modules"] != ONNX_EMPTY) == has_plugins, row["op"]
        assert row["next_action"], row["op"]

    for row in extra_rows:
        has_metadata = row["metadata"] == ONNX_CHECK
        has_lowering = row["lowering"] == ONNX_CHECK
        assert has_metadata or has_lowering, row["name"]
        assert row["modules"] != ONNX_EMPTY, row["name"]
        assert row["next_action"], row["name"]


def test_onnx_operator_coverage_has_no_official_metadata_lowering_asymmetry() -> None:
    text = _read_doc("docs/user_guide/onnx_operator_coverage.md")
    asymmetries = [
        f"{row['op']}: metadata={row['metadata']} lowering={row['lowering']}"
        for row in _onnx_main_rows(text)
        if row["metadata"] != row["lowering"]
    ]

    assert not asymmetries, (
        "Official ONNX operator coverage should not contain metadata/lowering "
        "asymmetries:\n" + "\n".join(asymmetries)
    )
