# Auto-generated by tests/t_generator.py
from tests.t_generator import generate_test_class

# Tests for examples2.nnx.CNN
generate_test_class(context='examples2.nnx', component='CNN', namespace=globals())

# Tests for examples2.nnx.MLP
generate_test_class(context='examples2.nnx', component='MLP', namespace=globals())

