from tests.t_generator import generate_test_class

generate_test_class("primitives.nnx", "nnx.avg_pool", globals())
generate_test_class("primitives.nnx", "nnx.batch_norm", globals())
generate_test_class("primitives.nnx", "nnx.conv", globals())
generate_test_class("primitives.nnx", "nnx.dot_product_attention", globals())
generate_test_class("primitives.nnx", "nnx.dropout", globals())
generate_test_class("primitives.nnx", "nnx.elu", globals())
generate_test_class("primitives.nnx", "nnx.gelu", globals())
generate_test_class("primitives.nnx", "nnx.layer_norm", globals())
generate_test_class("primitives.nnx", "nnx.leaky_relu", globals())
generate_test_class("primitives.nnx", "nnx.linear", globals())
generate_test_class("primitives.nnx", "nnx.linear_general", globals())
generate_test_class("primitives.nnx", "nnx.log_softmax", globals())
generate_test_class("primitives.nnx", "nnx.max_pool", globals())
generate_test_class("primitives.nnx", "nnx.relu", globals())
generate_test_class("primitives.nnx", "nnx.sigmoid", globals())
generate_test_class("primitives.nnx", "nnx.softmax", globals())
generate_test_class("primitives.nnx", "nnx.softplus", globals())
generate_test_class("primitives.nnx", "nnx.tanh", globals())
