# scripts/generate_readme.py

import argparse
import json
import logging
import os
import re
import subprocess
import sys
import time
import warnings
from pathlib import Path
from typing import Any
from tests.t_generator import get_plugin_grouping

os.environ.setdefault("JAX_PLATFORMS", "cpu")
warnings.filterwarnings(
    "ignore",
    message=r"Explicitly requested dtype <class 'jax\.numpy\.float64'>.*truncated to dtype float32",
    category=UserWarning,
)


# Configure logging
logging.basicConfig(level=logging.INFO, format="%(message)s")

# Paths
BASE_DIR = Path(__file__).parent
# COVERAGE_PATH = BASE_DIR / "../docs/readme/coverage_tables.md"  # Removed

COMPONENTS_PATH = BASE_DIR / "../docs/user_guide/supported_components.md"
EXAMPLES_PATH = BASE_DIR / "../docs/user_guide/examples.md"
REPORT_PATH = BASE_DIR / "output/pytest_report.json"
REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)  # Ensure output dir exists
EXAMPLES_TESTS_DIR = BASE_DIR.parent / "tests" / "examples"

# Markers for auto-generated sections in docs/readme/coverage_tables.md
START_MARKER = "<!-- AUTOGENERATED TABLE START -->"
END_MARKER = "<!-- AUTOGENERATED TABLE END -->"
EXAMPLES_START_MARKER = "<!-- AUTOGENERATED EXAMPLES TABLE START -->"
EXAMPLES_END_MARKER = "<!-- AUTOGENERATED EXAMPLES TABLE END -->"

# old: NETRON_BASE_URL = "https://netron.app/?url=https://enpasos.github.io/jax2onnx/onnx/"
NETRON_BASE_URL = "https://netron.app/?url=https://huggingface.co/enpasos/jax2onnx-models/resolve/main/"


# --- Running Tests ---
def run_generate_tests() -> None:
    """Runs the test-generation script and fails fast on errors."""
    logging.info("🧪 Generating tests...")
    subprocess.run(
        [sys.executable, str(BASE_DIR / "generate_tests.py")],
        check=True,
    )


def run_maxtext_tests() -> None:
    """Runs all generated MaxText tests when present."""
    maxtext_tests = sorted(EXAMPLES_TESTS_DIR.glob("test_maxtext*.py"))
    if not maxtext_tests:
        logging.info("ℹ️ No MaxText tests found after generation; skipping.")
        return

    logging.info("🧪 Running MaxText tests...")
    subprocess.run(
        [
            "python",
            "-m",
            "pytest",
            "-q",
            *[str(path) for path in maxtext_tests],
        ],
        check=True,
    )


def run_pytest() -> dict[tuple[str, str, str], str]:
    """Runs pytest and captures test results."""
    logging.info("🛠 Running tests...")

    try:
        subprocess.run(
            [
                "python",
                "-m",
                "pytest",
                "--json-report",
                f"--json-report-file={REPORT_PATH}",
            ],
            capture_output=True,
            text=True,
            check=False,
        )
    except subprocess.CalledProcessError as e:
        logging.error(f"❌ Pytest execution failed: {e}")
        return {}

    return parse_pytest_results()


def parse_pytest_results() -> dict[tuple[str, str, str], str]:
    """Parses pytest JSON report and extracts test results."""
    if not REPORT_PATH.exists():
        logging.warning("⚠️ No pytest report found.")
        return {}

    with REPORT_PATH.open("r", encoding="utf-8") as f:
        data = json.load(f)

    test_results = {}
    for test in data.get("tests", []):
        parts = test["nodeid"].split("::")

        if len(parts) == 3:
            partA, partB, partC = parts
        elif len(parts) == 2:
            partA, partC = parts
            partB = "NoClass"
        else:
            logging.warning(f"⚠️ Unexpected nodeid format: {test['nodeid']}")
            continue

        partAs = partA.split("/")
        if len(partAs) < 2 or partAs[1] not in {"examples", "primitives"}:
            continue

        if partC.startswith("test_"):
            testcase_name = partC[len("test_") :]
        else:
            testcase_name = partC
        situation = partAs[1]  # "examples" or "primitives"
        context = partAs[-1]
        if context.startswith("test_"):
            context = context[len("test_") :]
        if context.endswith(".py"):
            context = context[: -len(".py")]
        context = situation + "." + context
        if partB.startswith("Test_"):
            plugin = partB[len("Test_") :]
        else:
            plugin = partB

        status = "✅" if test["outcome"] == "passed" else "❌"
        key = (context, plugin, testcase_name)
        test_results[key] = status

    logging.info(f"✅ {len(test_results)} test results captured.")
    return test_results


# --- Metadata Processing ---
def merge_test_results(
    grouped: dict[tuple[str, str], list[dict[str, Any]]], test_results: dict
) -> dict[tuple[str, str], list[dict[str, Any]]]:
    """Ensures all metadata appears in tables, even if no test result exists."""
    for (context, component), testcases in grouped.items():
        for tc in testcases:
            tc_name = tc["testcase"]
            # Sanitize testcase name to match pytest nodeid convention (as in tests/t_generator.py)
            safe_tc_name = tc_name.replace(".", "_").replace(" ", "_").replace("-", "_")
            result = test_results.get(
                (context, component, safe_tc_name), "➖"
            )  # Always set a result
            url = f"{NETRON_BASE_URL}{context.replace('.', '/')}/{tc_name}.onnx"
            tc["result"] = f"[`{tc_name}`]({url}) {result}"
        grouped[(context, component)] = _dedupe_testcases(testcases)

    logging.info(
        f"📌 Merged {len(grouped)} grouped metadata entries with test results."
    )
    return grouped


def _dedupe_testcases(testcases: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Keep the first occurrence of each testcase name for doc tables."""
    seen: set[str] = set()
    deduped: list[dict[str, Any]] = []
    for testcase in testcases:
        testcase_name = str(testcase.get("testcase", ""))
        if testcase_name in seen:
            continue
        seen.add(testcase_name)
        deduped.append(testcase)
    return deduped


# --- Guard against silently dropping documented rows ---
_MD_LINK_RE = re.compile(r"^\[(?P<text>[^\]]+)\]\([^)]*\)$")
_ROW_LABEL_RE = re.compile(r"^\|\s*(?P<label>.+?)\s*\|")
_TABLE_HEADINGS = frozenset({"Component", "JAX Component"})


def _extract_section(content: str, start_marker: str, end_marker: str) -> str | None:
    """Return the text between the autogenerated markers, or None if absent."""
    start_idx = content.find(start_marker)
    end_idx = content.find(end_marker)
    if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
        return None
    return content[start_idx + len(start_marker) : end_idx]


def _row_labels(section: str) -> set[str]:
    """Return the first-column label of every data row in a generated table.

    Markdown links are reduced to their text so that a changed doc URL does not
    look like a dropped row.
    """
    labels: set[str] = set()
    for raw_line in section.splitlines():
        line = raw_line.strip()
        if not line.startswith("|"):
            continue
        match = _ROW_LABEL_RE.match(line)
        if match is None:
            continue
        label = match.group("label")
        if not label or set(label) <= set(":- "):
            continue
        if label in _TABLE_HEADINGS:
            continue
        link = _MD_LINK_RE.match(label)
        labels.add(link.group("text") if link else label)
    return labels


def _dropped_rows(
    existing_content: str, new_section: str, start: str, end: str
) -> set[str]:
    """Return labels documented today that the regenerated table would lose."""
    section = _extract_section(existing_content, start, end)
    if section is None:
        return set()
    return _row_labels(section) - _row_labels(new_section)


def _fail_on_dropped_rows(dropped: dict[Path, set[str]]) -> None:
    """Abort with an actionable message instead of silently shrinking a table."""
    lines = [
        "❌ Regenerating the coverage tables would remove rows that are currently",
        "   documented. This usually means an optional plugin world was not",
        "   registered, so its components never reached the metadata registry.",
        "",
    ]
    for path, labels in sorted(dropped.items(), key=lambda item: str(item[0])):
        preview = sorted(labels)
        shown = ", ".join(preview[:8])
        if len(preview) > 8:
            shown += f", … (+{len(preview) - 8} more)"
        lines.append(f"   {path.name}: {len(preview)} row(s) would disappear")
        lines.append(f"     {shown}")
    lines += [
        "",
        "   Run ./scripts/generate_readme.sh instead of this script directly: it",
        "   prepares the MaxText/MaxDiffusion checkouts that these rows need.",
        "   Alternatively set JAX2ONNX_MAXTEXT_SRC / JAX2ONNX_MAXDIFFUSION_SRC.",
        "",
        "   If the removal is intended (a plugin was deleted), re-run with",
        "   --allow-removals.",
    ]
    raise SystemExit("\n".join(lines))


# --- Coverage doc Update ---
def update_coverage_tables(
    grouped_metadata: dict[tuple[str, str], list[dict[str, Any]]],
    test_results: dict,
    allow_removals: bool = False,
):
    """Updates docs/readme/coverage_tables.md with new plugin and example tables."""
    plugins_grouped = {
        k: v for k, v in grouped_metadata.items() if k[0].startswith("primitives")
    }
    examples_grouped = {
        k: v for k, v in grouped_metadata.items() if k[0].startswith("examples")
    }

    plugins_grouped = merge_test_results(plugins_grouped, test_results)
    examples_grouped = merge_test_results(examples_grouped, test_results)

    new_plugins_section = generate_markdown_table(plugins_grouped, is_example=False)
    new_examples_section = generate_markdown_table(examples_grouped, is_example=True)

    targets = [
        (COMPONENTS_PATH, new_plugins_section, START_MARKER, END_MARKER),
        (
            EXAMPLES_PATH,
            new_examples_section,
            EXAMPLES_START_MARKER,
            EXAMPLES_END_MARKER,
        ),
    ]

    # Check every target before writing any of them, so an abort never leaves
    # one table regenerated and the other stale.
    pending: list[tuple[Path, str]] = []
    dropped: dict[Path, set[str]] = {}
    for path, new_section, start, end in targets:
        if not path.exists():
            logging.warning(f"⚠️ {path.name} not found.")
            continue
        content = path.read_text(encoding="utf-8")
        missing = _dropped_rows(content, new_section, start, end)
        if missing:
            dropped[path] = missing
        pending.append((path, replace_markers(content, start, end, new_section)))

    if dropped:
        if not allow_removals:
            _fail_on_dropped_rows(dropped)
        for path, labels in sorted(dropped.items(), key=lambda item: str(item[0])):
            logging.warning(
                f"⚠️ --allow-removals: dropping {len(labels)} row(s) from {path.name}."
            )

    for path, content in pending:
        path.write_text(content, encoding="utf-8")
        logging.info(f"✅ {path.name} updated successfully!")


def generate_markdown_table(
    grouped: dict[tuple[str, str], list[dict[str, Any]]], is_example: bool
) -> str:
    """Generates markdown table for docs/readme/coverage_tables.md, ensuring all metadata is included."""
    if is_example:
        header = (
            "| Component | Description | Testcases | Since |\n"
            "|:----------|:------------|:----------|:------|"
        )
        rows = []
        for (context, component), data in sorted(grouped.items()):
            description = data[0].get("description", "➖")
            # children = data[0].get("children", [])
            # children_str = "<br>".join(children) if children else "➖"
            testcases_str = "<br>".join(tc["result"] for tc in data) if data else "➖"
            since = data[0].get("since", "➖")  # Ensure "since" is included
            row = f"| {component} | {description} | {testcases_str} | {since} |"
            rows.append(row)

    else:
        header = (
            "| JAX Component | ONNX Components | Testcases | Since |\n"
            "|:-------------|:---------------|:---------|:------|"
        )
        rows = []
        for (context, component), data in sorted(grouped.items()):
            # Remove the leading "primitives." prefix from the context
            display_context = context.removeprefix("primitives.")

            comp_name = component.removeprefix("plugins.")
            # Add the context (like "jnp") as a prefix to the component name
            prefixed_comp_name = f"{display_context}.{comp_name}"
            jax_doc = data[0].get("jax_doc")
            if jax_doc and str(jax_doc).startswith("http"):
                jax_comp = f"[{prefixed_comp_name}]({jax_doc})"
            elif jax_doc and jax_doc != "➖":
                jax_comp = f"{prefixed_comp_name} ({jax_doc})"
            else:
                jax_comp = prefixed_comp_name
            onnx_components = (
                "<br>".join(
                    sorted([f"[{x['component']}]({x['doc']})" for x in data[0]["onnx"]])
                )
                if data[0]["onnx"]
                else "➖"
            )
            testcases_str = "<br>".join(tc["result"] for tc in data) if data else "➖"
            since = data[0].get("since", "➖")
            row = f"| {jax_comp} | {onnx_components} | {testcases_str} | {since} |"
            rows.append(row)

    logging.info(f"📋 Generated {len(rows)} table rows.")
    table_md = f"{header}\n" + "\n".join(rows)
    class_name = "examples-table" if is_example else "coverage-table"
    return f'<div class="{class_name}" markdown="1">\n\n{table_md}\n\n</div>'


def replace_markers(
    content: str, start_marker: str, end_marker: str, new_section: str
) -> str:
    """Replaces section between markers in docs/readme/coverage_tables.md, ensuring no data loss."""
    start_idx = content.find(start_marker)
    end_idx = content.find(end_marker)
    if start_idx == -1 or end_idx == -1:
        logging.error(
            f"❌ Markers `{start_marker}` or `{end_marker}` not found in docs/readme/coverage_tables.md"
        )
        return content

    return (
        content[:start_idx]
        + f"{start_marker}\n\n{new_section}\n\n{end_marker}"
        + content[end_idx + len(end_marker) :]
    )


# --- Main Execution ---
def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate the coverage tables. Prefer ./scripts/generate_readme.sh, "
            "which prepares the optional MaxText/MaxDiffusion checkouts first."
        )
    )
    parser.add_argument(
        "--allow-removals",
        action="store_true",
        help=(
            "Write the tables even when rows that are documented today would "
            "disappear. Only use this when a plugin was deliberately removed."
        ),
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    start_time = time.time()
    run_generate_tests()
    run_maxtext_tests()
    test_results = run_pytest()
    grouped_metadata = get_plugin_grouping()
    update_coverage_tables(
        grouped_metadata, test_results, allow_removals=args.allow_removals
    )
    logging.info(f"⏳ Total execution time: {time.time() - start_time:.2f}s")
