# Auto-generated by tests/t_generator.py
from tests.t_generator import generate_test_class

# Tests for primitives2.nnx.batch_norm
generate_test_class(
    context="primitives2.nnx", component="batch_norm", namespace=globals()
)

# Tests for primitives2.nnx.dropout
generate_test_class(context="primitives2.nnx", component="dropout", namespace=globals())

# Tests for primitives2.nnx.linear
generate_test_class(context="primitives2.nnx", component="linear", namespace=globals())

# Tests for primitives2.nnx.linear_general
generate_test_class(
    context="primitives2.nnx", component="linear_general", namespace=globals()
)
