# Auto-generated by tests/t_generator.py
from tests.t_generator import generate_test_class

# Tests for primitives2.nnx.linear
generate_test_class(context="primitives2.nnx", component="linear", namespace=globals())
