# Auto-generated by tests/t_generator.py
from tests.t_generator import generate_test_class

# Tests for primitives2.nnx.avg_pool
generate_test_class(context='primitives2.nnx', component='avg_pool', namespace=globals())

# Tests for primitives2.nnx.batch_norm
generate_test_class(context='primitives2.nnx', component='batch_norm', namespace=globals())

# Tests for primitives2.nnx.conv
generate_test_class(context='primitives2.nnx', component='conv', namespace=globals())

# Tests for primitives2.nnx.dropout
generate_test_class(context='primitives2.nnx', component='dropout', namespace=globals())

# Tests for primitives2.nnx.gelu
generate_test_class(context='primitives2.nnx', component='gelu', namespace=globals())

# Tests for primitives2.nnx.linear
generate_test_class(context='primitives2.nnx', component='linear', namespace=globals())

# Tests for primitives2.nnx.linear_general
generate_test_class(context='primitives2.nnx', component='linear_general', namespace=globals())

# Tests for primitives2.nnx.relu
generate_test_class(context='primitives2.nnx', component='relu', namespace=globals())

# Tests for primitives2.nnx.softmax
generate_test_class(context='primitives2.nnx', component='softmax', namespace=globals())

# Tests for primitives2.nnx.softplus
generate_test_class(context='primitives2.nnx', component='softplus', namespace=globals())

# Tests for primitives2.nnx.tanh
generate_test_class(context='primitives2.nnx', component='tanh', namespace=globals())

